version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 #//host.docker.internal:9092 - dùng để chỉ đia chỉ máy thật tử container "kafka" này -> kafka sau đó "quảng bá" địa chỉ này -> các ứng dụng trên local "nằm ngoài docker" có thể kết nối đến thông qua localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
